version: '3.1'

services:

  wordpress:
    # image: wordpress:php8.2
    container_name: challenge_coffe_code
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: coffecode
      WORDPRESS_DB_PASSWORD: coffecode@P455
      WORDPRESS_DB_NAME: challenge
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins:rw

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: challenge
      MYSQL_USER: coffecode
      MYSQL_PASSWORD: coffecode@P455
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db: